export const GAME_CONFIG = {
  flightDuration: 90,
  maxLives: 3,
  maxDepth: 4,
  spawnInterval: 1.5,
  maxTraces: 2,
  hitStopDuration: 0.05,
  traceSpeed: 18,
  projectileSpeed: 72,
  fieldWidth: 13,
  fieldMinY: -2.5,
  fieldMaxY: 2.7,
  keyboardMoveSpeed: 9,
  keyboardMoveSpeedY: 7,
} as const;
